name: dockerbuild

on:
  push:
    branches: [1.3.0] 
jobs:
  main:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
         - app: frontend
           path: frontend
           version: nightly
           experimental: true
         - app: backend
           path: backend
           version: nightly
           experimental: true
         - app: app_sdk 
           path: backend/app_sdk
           version: nightly
           experimental: true 
         - app: orborus
           path: functions/onprem/orborus
           version: nightly
           experimental: true 
         - app: worker 
           path: functions/onprem/worker
           version: nightly
           experimental: true 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
          
      - name: Login to Ghcr 
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Ghcr Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        env:
          BUILDX_NO_DEFAULT_LOAD: true
        with:
          logout: false
          context: ${{ matrix.path }}/
          file: ${{ matrix.path }}/Dockerfile          
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            ghcr.io/gsoc2/gsoc2-${{ matrix.app }}:nightly
            ${{ secrets.DOCKERHUB_USERNAME }}/gsoc2-${{ matrix.app }}:nightly

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
